version: 1.0.{build}
before_build:
- nuget restore
build:
  project: WhereIsMyColleague.sln
  publish_wap: true
  verbosity: minimal
deploy:
- provider: WebDeploy
  server: https://whereismycolleague.scm.azurewebsites.net:443/msdeploy.axd?site=whereismycolleague
  website: whereismycolleague
  username: $whereismycolleague
  password:
    secure: epX63djwCcNjxpwWLCd5KP2rjTQGHKfo4FTY+uIKq1gJCdaZix0Dw6XD2SvWQvFKcN9QkbFw993Plwpb41JlNg==
  remove_files: true
  app_offline: true
  artifact: WhereIsMyColleague.Web.zip
  on:
    branch: master
- provider: WebDeploy
  server: https://where-is-fred.scm.azurewebsites.net:443/msdeploy.axd?site=where-is-fred
  website: where-is-fred
  username: $where-is-fred
  password:
    secure: 7Iee2xCtOBMj5900kcoRSuLu1O3AUeFPSz3nob/WTParsuR9NGGHrymaKcKTRjravlRpoKj2wLw2HA7+Q6F4GA==
  remove_files: true
  app_offline: true
  artifact: WhereIsMyColleague.API.zip
  on:
    branch: master
notifications:
- provider: Slack
  channel: wfhsite
  auth_token:
    secure: mWg4X/XBMQKvqyywkdki6Py9mhMezKro6spSAtgJIaTsI0I9wogumgzHcH+Bd6+P
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
